### ISSUE TITLE
Failure to add plex repo to ubuntu 18.04

### ISSUE THREAD

**Issue by danielloader** [wilmardo/ansible-plex#12]
`
TASK [wilmardo.plex : Add Plex apt repo (Ubuntu & Debian with systemd)] **************************************************************************************************************************
fatal: [192.168.122.160]: FAILED! => {"changed": false, "msg": "E:The repository 'https://downloads.plex.tv/repo/deb ./public Release' does not have a Release file."}
`

Hello, thanks for the role but on running it as described with the documentation on a completely new blank ubuntu server 18.04 install I get the above error.

Anything I can do to debug it for you?

**Comment by danielloader** [comment]
Noticed there's a PR for this already - nevermind!

**Comment by wilmardo** [comment]
Ans this should be resolved now, thanks for raising the issue 💯
